[tool.poetry]
name = "subwhisper"
version = "0.1.1"
description = ""
authors = ["tupiznak <akej-vonavi@mail.ru>"]
readme = "README.md"
packages = [
    { include = "subwhisper" },
]


[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
